version: '2'
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "32769:5432"
  web:
    container_name: web
    build: .
    image: web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
